### ISSUE TITLE
Not working with self-signed HTTPS certificates

### ISSUE THREAD

**Issue by mjacoby** [admin-shell-io/aas-test-engines#11]
When running the API test against a server using a self-signed SSL certificate I receive the following error message

> Failed to reach: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))

Any tips on how I can resolve this? Can I even do this on my end (e.g. using CLI arguments or environment variables) or does this require code changes on your side?

FYI, if you need a server with self-signed certificate to reproduce the error or test against, you can use [FA³ST Service](https://github.com/FraunhoferIOSB/FAAAST-Service), e.g. just start it via docker container with `docker run -p 443:443 fraunhoferiosb/faaast-service:1.0.0`

**Comment by otto-ifak** [comment]
Thanks for reporting this @mjacoby. We will address this with the upcoming release.

**Comment by otto-ifak** [comment]
Implemented as follows now:

Usign cli:
```sh
python -m aas_test_engines check_server https://localhost --suite 'Asset Administration Shell API' --no-verify
```

Usign the python interface:
```python
from aas_test_engines import api

tests = api.generate_tests('3.0', set(['Asset Administration Shell API']))
exec_conf = api.run.ExecConf(
    server="http://localhost",
    verify=False,
)
api.execute_tests(tests, exec_conf)
```
