### ISSUE TITLE
Optional but empty arrays are considered an error

### ISSUE THREAD

**Issue by otto-ifak** [admin-shell-io/aas-test-engines#15]
Currently, arrays which are optional (i.e. not required) are considered as an error when present but empty.
Eg:
```json
{
  "conceptDescriptions": []
}
```
is currently rejected.

We need to clarify if this is compliant to the spec.

**Comment by otto-ifak** [comment]
See also https://github.com/admin-shell-io/aas-test-engines/issues/13#issuecomment-2044698045

**Comment by otto-ifak** [comment]
I would argue for removing `minItems: 1` from https://github.com/admin-shell-io/aas-test-engines/blob/main/aas_test_engines/data/file/3.0.yml then (currently 28 instances)

**Comment by sebbader-sap** [comment]
The desired behaviour, as agreed in the AAS Specification working group, is that no empty `conceptDescriptions` array is present. Therefore, the `minItems: 1` clauses are correct.

**Comment by sebbader-sap** [comment]
> We need to clarify if this is compliant to the spec.

It is :-)

**Comment by otto-ifak** [comment]
Great, thanks @sebbader-sap for clarifying this!

**Comment by juileetikekar** [comment]
Related issue in the specifications, https://github.com/admin-shell-io/aas-specs/issues/418
