### ISSUE TITLE
Acceptance Tests for REST API Testing

### ISSUE THREAD

**Issue by otto-ifak** [admin-shell-io/aas-test-engines#19]
Currently, there are acceptance tests for file testing only. We also need these to verify correctness of the API Test as well.

**Comment by otto-ifak** [comment]
As we decided for basxy as SUT, the following bugs need to fixed first:

* https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/279

**Comment by juileetikekar** [comment]
Fixed.
