### ISSUE TITLE
Support API Test for Discovery Service Specification

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-test-engines#23]
One of the high priority service specifications is the one for discovery. It still seems to be missing.

![image](https://github.com/admin-shell-io/aas-test-engines/assets/59824205/7dcd58ca-f523-468b-a0fd-180471beb8dc)

**Comment by juileetikekar** [comment]
The issue lies in the Certification Portal and not in the test-engine.

**Comment by BirgitBoss** [comment]
where to put issues for the Certification Portal?

**Comment by otto-ifak** [comment]
As the portal is currently under re-design (and disabled anyway), there is currently no way to report these.
