### ISSUE TITLE
Improve usability of error report

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-test-engines#29]
Please improve error report, it is extremely difficult to read

This is an extract of the error report of a Submodel Template (not yet released)

![image](https://github.com/admin-shell-io/aas-test-engines/assets/59824205/35c7b03b-1fd9-492d-be97-728bded2defa)

Examples:
1) instead of "item 0" use idShortPath to clarify which SubmodelElement exactly you are talking about (this is not a SML)
2) Enable Export and some kind of tracking of errors (i.e. one line per error)
...

**Comment by otto-ifak** [comment]
Thanks for the suggestion. Due to limited resources, we will have a look at this later.

**Comment by juileetikekar** [comment]
Related to #55

**Comment by juileetikekar** [comment]
Readability is fixed (currently in a branch, but will be merged into main this week).
