### ISSUE TITLE
Check of XML in check_aasx_file is not working

### ISSUE THREAD

**Issue by bittnalSICKAG** [admin-shell-io/aas-test-engines#32]
When I tested the tool, I only ever found the built-in errors in the XML file when I called ` file.check_xml_file(f)` on the unpacked XML file. With `file.check_aasx_file(f)` the built-in errors in the XML in the AASX file were not found, e.g. missing AAS ID or errors in the namespace. How can that be?

**Comment by otto-ifak** [comment]
Could you provide the AASX file to reproduce the issue?

**Comment by bittnalSICKAG** [comment]
I found the issue in my aasx - i used the wrong relationship type: "https://www.admin..." instead of "https://admin...". It works now.

Thanks anyways!

**Comment by otto-ifak** [comment]
No problem, thanks for trying out the Test Engines :)
