### ISSUE TITLE
Implement Bugfix release IDTA-0100x

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-test-engines#34]
Please implement the bugfixes as defined in the bugfix releases of the AAS Specification: https://industrialdigitaltwin.org/content-hub/aasspecifications

IDTA-01001-3-0-1
IDTA-01002-3-0-2
IDTA-01003-a-3-0-1
IDTA-01005-3-0-1

**Comment by otto-ifak** [comment]
Have the corresponding swagger specs for these already been released?

**Comment by otto-ifak** [comment]
- [ ] IDTA-01001-3-0-1
- [ ] IDTA-01002-3-0-2
- [ ] IDTA-01003-a-3-0-1
- [ ] IDTA-01005-3-0-1

**Comment by otto-ifak** [comment]
IDTA-01001-3-0-1: Done in e00f4145dca11bcde99067468fdb24f46e176ec

**Comment by otto-ifak** [comment]
IDTA-01002-3-0-2: Done in 7b1508900d1c89e29d533a972cd1a8b390d449ec

**Comment by otto-ifak** [comment]
IDTA-01005-3-0-1 done in  6bd5ac83cb05c8cb53dedd8e80453d1f876f9353

**Comment by otto-ifak** [comment]
IDTA-01003-a-3-0-1: nothing to do
