### ISSUE TITLE
Indicate validation result in process exit code

### ISSUE THREAD

**Issue by atextor** [admin-shell-io/aas-test-engines#38]
When I run the validation from the commandline, e.g. `python -m aas_test_engines check_file MyFile.aasx`, I would like the process to return an exit code of `0` if and only if the file validated successfully (raises no warnings or errors).
I suggest returning `1` for all other cases, but of course you could return distinct codes for "raises errors" and "raises (only) warnings".

**Comment by otto-ifak** [comment]
Great idea, thanks
