### ISSUE TITLE
Issue with API Validation: /shells/INVALID

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#39]
In case of API validation "Asset Administration Shell Repository API", the test-engine triggers GET "/shells/INVALID" API call, equivalient to "/shells/{aasIdentifier}", where the parameter aasIdentifier needs to be Base64Url Encoded. However, "INVALID" is a valid Base64Url encoding. Therefore, the AAS Server returns NotFound (404) status code. But the test-engine expects BadRequest (400), which is unexpected.

Screenshot from test-engine:
![image](https://github.com/user-attachments/assets/6f523225-fcc7-44f8-bc2f-e5cb84edc818)

**Comment by otto-ifak** [comment]
Has been fixed, no invokes `GET /shells/x`, and only once
