### ISSUE TITLE
Transparancy about validation (checkpoints)

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/aas-test-engines#4]
I did some testing (AASX-File, Package Explorer V3.0 generated) with this great new service and got some questions.

1) A test failed due to missing concept description (no CD in the AASX). Is at least one CD mandatory? Is this specified somewhere?
2) I tested an AAS and got the protocol below

* Is there a list of check points that are checkend by this service and that could be referenced in the protocol?
* In the protocol there is not clear what the items are and what the problem is

I am aware that this is still in development. So this issue is just to give early feedback to you.

**A transparent list with all checks that are performed would be helpful!**

![image](https://github.com/admin-shell-io/aas-test-engines/assets/118162568/4bfc99d8-57b1-4cb3-9c09-4961f9089d44)

**Comment by otto-ifak** [comment]
Hello @foprs, thanks for reporting this issue. 
1. A CD is optional, but if you provide one, it must not be empty (see https://github.com/admin-shell-io/aas-specs/blob/f4662a61cb7cdb180a779da38b409e7ead749628/schemas/json/aas.json#L584)
2. Multiple people reported similar problems, so we will address this in the next release

**Comment by otto-ifak** [comment]
Fixed by updating the underlying JSON schema library - you now get much more information when validating arrays.
