### ISSUE TITLE
Issue with API Validation: /shells/INVALID twice

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#40]
In case of API validation "Asset Administration Shell Repository API", the test-engine triggers GET "/shells/INVALID" API call twice.

![image](https://github.com/user-attachments/assets/399b3cb5-b8e6-4653-9ca7-6a269418ff7a)

**Comment by otto-ifak** [comment]
Has been fixed, no invokes `GET /shells/x`, and only once
