### ISSUE TITLE
Issue with API Validation: /shells/random_string

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#42]
In case of API validation "Asset Administration Shell Repository API", the test-engine triggers GET "/shells/random_string" API call, equivalient to "/shells/{aasIdentifier}", where the parameter aasIdentifier needs to be Base64Url Encoded. However, "random_string" is an  invalid Base64Url encoding. Therefore, the AAS Server returns Badrequest (400) status code. But the test-engine expects Success (200), which is unexpected.

Screenshot from test-engine
![image](https://github.com/user-attachments/assets/969eba4e-5b5b-46e0-9eb1-f8fd95705966)

**Comment by otto-ifak** [comment]
Fixed, it cares about the base64 encoding now
