### ISSUE TITLE
API Validation: GetAllAssetAdministrationShells-Reference

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#46]
In case of API validation " AssetAdministrationShellRepositoryServiceSpecification/SSP-002", the test-engine triggers "GetAllAssetAdministrationShells-Reference" (/shells/$reference) API Call. In this call the test-engine generates "Failed: Cannot look up idShort: 'idShort'" error. From this error, it is hard to understand, exactly what has failed.

Screenshot:
![image](https://github.com/user-attachments/assets/594cebb3-cf7d-437c-99ea-e5b045f458d5)

**Comment by otto-ifak** [comment]
Fixed (see #60)
