### ISSUE TITLE
Documentation for Validation Coverage

### ISSUE THREAD

**Issue by bittnalSICKAG** [admin-shell-io/aas-test-engines#47]
Hello, 
it would be very helpful to have a documentation or a list of violations in an AAS which are detectable and which (known) are not.  
E.g. 
- which values of properties are checked against a pattern
- are the submodels checked against their templates
- ...

**Comment by juileetikekar** [comment]
Related to #18

**Comment by juileetikekar** [comment]
Hi @bittnalSICKAG,

Please have a look into the README and [Transparency List](https://github.com/admin-shell-io/aas-test-engines/tree/main/doc) document for more details. If you find something missing, feel free to reopen the issue.
