### ISSUE TITLE
API Validation:  /shells/{aasIdentifier}/submodels

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#48]
In case of API validation " AssetAdministrationShellRepositoryServiceSpecification/SSP-002", the test-engine triggers "/shells/{aasIdentifier}/submodels" API call. However, such API operation does not exist either in Part 2 specifications or [SwaggerHub Definitions](https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShellRepositoryServiceSpecification/V3.0.2_SSP-001#/Asset%20Administration%20Shell%20Repository%20API/PatchSubmodelById-Metadata_AasRepository). 

![image](https://github.com/user-attachments/assets/4b109da8-bf0b-448b-98ab-6315afd7a0e3)

**Comment by juileetikekar** [comment]
Related issue https://github.com/eclipse-aaspe/server/issues/335

**Comment by otto-ifak** [comment]
Close for now, maybe we reopen it if this endpoint is added.
