### ISSUE TITLE
API Validation: GetSubmodelById_AasRepository & GetAllSubmodelElements_AasRepository

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#49]
In case of API validation " AssetAdministrationShellRepositoryServiceSpecification/SSP-002", the test-engine triggers /shells/{aasIdentifier}/submodels/{submodelIdentifier} (GetSubmodelById_AasRepository). However, in the request the test-engine does not provide in submodelIdentifier.

![image](https://github.com/user-attachments/assets/27663d47-5b06-4102-942b-3182f0717b5a)

**Comment by juileetikekar** [comment]
Similar behavior for GetAllSubmodelElements_AasRepository:

![image](https://github.com/user-attachments/assets/f8dcc3ed-5ff7-4a67-8839-81f676ba56bc)

**Comment by otto-ifak** [comment]
Fixed by https://github.com/admin-shell-io/aas-test-engines/commit/88f550ae3e0b063829f62b40d68bf13e2d4c8aed
