### ISSUE TITLE
Unknown ref #/components/schemas/GetSubmodelElementsMetadataResult when calling generate_tests for the API

### ISSUE THREAD

**Issue by MMuellerMitsubishi** [admin-shell-io/aas-test-engines#5]
I have installed the latest version through pip install and I'm trying to execute the sample code for testing our API.

The function generate_tests for the api throws the following exception
Unknown ref #/components/schemas/GetSubmodelElementsMetadataResult

I assume this is not related to our API but a general issue with the schema definitons.

Kindly ask for support in case we are doing anything wrong here.

![image](https://github.com/admin-shell-io/aas-test-engines/assets/81679020/95d9f07c-6ccb-4ea4-8d33-f615151b9990)

**Comment by otto-ifak** [comment]
Thanks @MMuellerMitsubishi for this issue, this seems to be a bug on our side. I will have a look at it.

**Comment by otto-ifak** [comment]
The python package has been published right now (version 0.3.0).
