### ISSUE TITLE
API Validation: GenerateSerializationByIds

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#51]
In case of API validation " AssetAdministrationShellRepositoryServiceSpecification/SSP-002", the test-engine triggers /serialization (GenerateSerializationByIds) API Call. This API consists of query parameters aasIds (list of Base64URL encoded aasIds), submodelIds (list of Base64URL encoded submodelIds) & includeConceptDescriptions (boolean). However, in the second iteration of semantic testing, the test-engine sends nothing in aasIds and submodelIds, and encoded includeConceptDescription. In this case, the test-engine expects 200, which is unexpected.

![image](https://github.com/user-attachments/assets/abe5ee62-3a64-4dd6-ad5e-e43cfd551490)

**Comment by otto-ifak** [comment]
All three parameters are optional so it should be fine to call `/serialization`. Or am I missing something?

**Comment by otto-ifak** [comment]
Btw: This endpoint seems to be broken in AAS server as it returns 500.

**Comment by juileetikekar** [comment]
Yes, the three parameters are optional. The third parameter "includeConceptDescription" is boolean. Therefore, if the first two parameters "aasIds" & "submodelIds" are not set, and "includeConceptDescription" is set to either true or false, ideally the call looks as below:

GET /serialization?**includeConceptDescriptions=false**

As per the screenshot, the test-engine provides some sort of formatted boolean, for instance: "**%5B%27false%27%5D**", which is unexpected.
