### ISSUE TITLE
API Validation: GetDescription

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#52]
In case of API validation " AssetAdministrationShellRepositoryServiceSpecification/SSP-002", the test-engine triggers /description (GetDescription) API Call. Even though the server response consists of "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002", the test-engine gives a warning that "AssetAdministrationShellRepositoryServiceSpecification/SSP-002" is not part of profiles.

Screenshot:
Server Response:
![image](https://github.com/user-attachments/assets/326af65b-cdd7-40ba-b608-e138aa264ced)

result of test engine
![image](https://github.com/user-attachments/assets/89f7115b-830f-4531-bf61-9b28cf1ad876)

**Comment by otto-ifak** [comment]
@juileetikekar  Should be fixed, could you please re-check? The official docker image still returns the old profile names.
