### ISSUE TITLE
API Validation: GetAllAssetAdministrationShellsByAssetId missing

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#53]
In case of API validation " AssetAdministrationShellRepositoryServiceSpecification/SSP-002", GetAllAssetAdministrationShells with query parameter AssetId API call is missing.

![image](https://github.com/user-attachments/assets/f14b2c70-5594-4287-98d5-06811062ba97)

**Comment by otto-ifak** [comment]
Fixed. However, I had to include this in the `GetAllAssetAdministrationShells` operation, since OpenAPI spec defines it that way.
