### ISSUE TITLE
 Test Engine Performance with Large AAS Files

### ISSUE THREAD

**Issue by Rudra-sandeep** [admin-shell-io/aas-test-engines#54]
I have encountered a performance issue with our test engine when processing large AAS files.The test engine currently takes too long to generate results for large aas files.

**Comment by otto-ifak** [comment]
Hi @Rudra-sandeep thanks for reporting this. How large is your AAS file? Could you provide a sample?

**Comment by Rudra-sandeep** [comment]
@otto-ifak I attached the file
[test_engine.json](https://github.com/user-attachments/files/16835545/test_engine.json)

**Comment by otto-ifak** [comment]
Thanks, I will have a look.

**Comment by juileetikekar** [comment]
Improved
