### ISSUE TITLE
 Readability of error messages

### ISSUE THREAD

**Issue by Rudra-sandeep** [admin-shell-io/aas-test-engines#55]
suggestions to improve error messages for better readability

Test engine error message
item 17 is invalid
               Reference #/$defs/ConceptDescription is invalid
                  Does not match all sub-schemas
                     Reference #/$defs/HasDataSpecification is invalid
                        Property embeddedDataSpecifications is invalid
                           item 0 is invalid
                              Reference #/$defs/EmbeddedDataSpecification is invalid
                                 Property dataSpecificationContent is invalid
                                    Reference #/$defs/DataSpecificationContent_choice is invalid
                                       Does not match at least one sub-schema
                                          Reference #/$defs/DataSpecificationIec61360 is invalid
                                             Does not match all sub-schemas
                                                Property value is invalid
                                                   Value is shorter than 1
      Suggestions:
      KeyError: 'Failed to construct {https://admin-shell.io/aas/3/0}definition on line 602 using construct_definition_type_iec61360!'
      ValueError: Failed to construct {https://admin-shell.io/aas/3/0}multiLanguageProperty on line 190 using 
                        construct_submodel_element!
      ValueError: Failed to construct {https://admin-shell.io/aas/3/0}reference on line 16 using _construct_submodel_reference!

**Comment by juileetikekar** [comment]
Related to #29

**Comment by juileetikekar** [comment]
Fixed.
