### ISSUE TITLE
SMT Validation throws an Invalid Error

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#58]
An SMT validation throws "Relationship has non-existing target aasx\aasx-origin" error.

![image](https://github.com/user-attachments/assets/1e93f5ef-98a4-4d2d-ac54-a8fec4d5c741)

Related to #35

**Comment by otto-ifak** [comment]
@juileetikekar  As #35 is fixed now, could you provide some update about this issue?

**Comment by juileetikekar** [comment]
The issue mentioned above is fixed. The issue can be closed now.
