### ISSUE TITLE
API Validation: GetAllAssetAdministrationShells with limit

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#60]
The test-engine invokes "GET /shells?limit=1" on the server with only one AAS and shows the error "Failed: Cannot look up paging_metadata/cursor: key 'cursor' does not exist". 

![image](https://github.com/user-attachments/assets/e8225885-ad62-4ec1-88e7-8366e85d5764)

However, as per the specifications, if the end of the result has been reached, the cursor should not be set in the Result object. That means, if the server has only 1 AAS, and the client sends the limit of 1, then in response, cursor will be not be present. 

![image](https://github.com/user-attachments/assets/0055735a-0c44-4265-b2d1-c0c121e320f0)

However, the test-engine shows the error currently.

**Comment by juileetikekar** [comment]
Similar behavior in case of GET /shells/$reference?limit=1

**Comment by otto-ifak** [comment]
Fixed, test engines now give a warning instead of an error:
![image](https://github.com/user-attachments/assets/8f2e1cae-92ca-43f0-af20-f52f92b49fe9)
