### ISSUE TITLE
Question on Interpreting Validation Results from aas_test_engines

### ISSUE THREAD

**Issue by sirius910b** [admin-shell-io/aas-test-engines#69]
Hello, thank you very much for your great work, which has helped me tremendously in studying AAS.

I have run the following code to apply the validate function from aas_test_engines, and I have attached the results (as result.dump() values) in separate text files.

[TRY1]
from aas_test_engines import file

with open('05_Bosch.aasx', 'rb') as f:
    result = file.check_aasx_file(f)
result.ok() == True

result.dump()

[TRY2]
from aas_test_engines import file

\# Check file
with open('05_Bosch.json') as f:
    result = file.check_json_file(f)
result.ok() == True

result.dump()

[TRY3]
from aas_test_engines import file
from xml.etree import ElementTree

\# Check file
with open('05_Bosch.xml', encoding='utf-8') as f:
    result = file.check_xml_file(f)
    
result.dump()

## [Question]
I am unsure how to interpret the result.dump() values, and there seem to be too many invalid results. Just in case, I have also attached the original AASX file that has been converted to JSON.

Thank you

[[TRY1] - Result.txt](https://github.com/user-attachments/files/17433499/TRY1.-.Result.txt)
[[TRY2] - Result.txt](https://github.com/user-attachments/files/17433501/TRY2.-.Result.txt)
[[TRY3] - Result.txt](https://github.com/user-attachments/files/17433508/TRY3.-.Result.txt)
[05_Bosch.json](https://github.com/user-attachments/files/17433523/05_Bosch.json)

**Comment by otto-ifak** [comment]
Hi @sirius910b , seems that your file violates multiple constraints, including AASd-122 and AASd-125.

**Comment by otto-ifak** [comment]
(related to #55)

**Comment by juileetikekar** [comment]
Fixed the readability of the error messages.

**Comment by otto-ifak** [comment]
Closed as this issue appears to be closed. Feel free to re-open if neccessary.
