### ISSUE TITLE
Validation on Constraint_AASc-3a-010

### ISSUE THREAD

**Issue by lukwitt** [admin-shell-io/aas-test-engines#70]
Hello,

I have a question about the validation result against the constraint Constraint_AASc-3a-010. In Part 3 of the specification, it is defined for this constraint that both value and valuelist can be empty for concept descriptions that define the semantics of a property. In my attached example, however, the test engine still produces an error. Is there a modelling error here or is the check too restrictive?

[Example_Constraint_Testing.zip](https://github.com/user-attachments/files/17660375/Example_Constraint_Testing.zip)

**Comment by otto-ifak** [comment]
Hi @lukwitt this was indeed a bug in the Test Engines.
However, we've already fixed it, so that in the latest version your file is accepted.
