### ISSUE TITLE
Plans for typescript or another language

### ISSUE THREAD

**Issue by Dorocy** [admin-shell-io/aas-test-engines#71]
thank you for providing and developing this open source library. 
i am wondering if there are any plans to release this test engine based on typescript or another language? 
if so, could you share when we might expect to see it?
thanks.

**Comment by otto-ifak** [comment]
@Dorocy We currently do not plan to release the Test Engines in another language.
If you want to integrate them into your program, the best solution would be to use the command line in combination with `--ouput json` . If you are only interested in pass/fail, the cli returns a zero error code if the test passes.
