### ISSUE TITLE
suite shall reflect standardized service profiles

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-test-engines#8]
Currently there are suites defined like

aas_read, aasx_read etc.

However, it is not clear what is tested here: the profiles do have unique identifiers and are versioned. So the suite shall reflect the profile IDs, e.g.

https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001
https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002

If abbreviations are introduced they still need to include version and profile number information and a clear mapping needs to be defined.

P.S. Also Interfaces do have unique Identifiers, so perhaps the suite test interfaces but no profiles?

**Comment by otto-ifak** [comment]
@BirgitBoss Thanks for the hint. As the SSPs are basically read and read/write, we thought we would already cover these correctly.
We will discuss how to handle this.

**Comment by otto-ifak** [comment]
We finally decided to follow you proposal.
For the naming of test suites we follow the names given by the specification. These are:
* APIs: Asset Administration Shell API, Submodel API, ...
* Service Specifications: Asset Administration Shell Service Specification, Submodel Service Specification, ...
* Profiles: AssetAdministrationShellServiceSpecification/SSP-001, ...

For profiles, we drop the prefix for better readability. The spec version has to be provided by the user anyway.
